name: sispmctl
license: GPL-2.0-or-later
version: '4.10'
grade: stable
summary: Silver Shield PM Control for Linux (sispmctl)
source-code: https://sourceforge.net/p/sispmctl/git/
issues: https://sourceforge.net/p/sispmctl/_list/tickets
description: |
  SiS-PM Control for Linux provides a management software
  for the following USB controlled powerstrips::

  * Gembird SIS-PMS SilverShield
  * Gembird MSIS-PM
  * EnerGenie EG-PMS2
  * EnerGenie EG-PMS2

  The following manual step is required to connect to USB::

      snap connect sispmctl:raw-usb

  If you want to use sispmctl as an unpriviledged user,
  you will have to execute the following manual steps

    sudo groupadd -r sispmctl
    sudo usermod -a -G sispmctl $USER
    sudo cp \
      /snap/sispmctl/current/share/doc/sispmctl/examples/60-sispmctl.rules \
      /lib/udev/rules.d/

base: core20

confinement: strict

apps:
  sispmctl:
    command: bin/sispmctl
    plugs:
      - raw-usb

parts:
  sispmctl:
    source: http://download.sourceforge.net/project/sispmctl/sispmctl/sispmctl-4.10/sispmctl-4.10.tar.gz
    source-checksum: sha256/e648b6e87584330a0a693e7b521ebbc863608d6c97ef929063542b459d16bc6f
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
      - --enable-webless
    build-packages:
      - autotools-dev
      - libusb-dev
      - pkg-config
    stage-packages:
      - libusb-0.1-4
